version: "3.9"

services:
  web:
    image: scuadrosf/smilelink:v1
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost/smilelink
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password.12345
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
    ports:
      - 8443:8443
    depends_on:
      - db
  db:
    image: mysql:8.0.22
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password.12345
      - MYSQL_DATABASE=smilelink
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - 3307:3306